version: '3.1'
services:
  mongo:
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./containers/mongo/data:/data/db
    image: mongo:8.0.0-rc9
    restart: always
    env_file: .env
    networks:
      - network-test
  mysql:
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./containers/mysql/data:/var/lib/mysql
    image: mysql:5.7
    restart: always
    env_file: .env
    networks:
      - network-test
networks:
  network-test:
  # backend:
  #   container_name: backend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./backend:/app
  #   image: node:lts-slim
  #   working_dir: /app 
  #   depends_on:
  #     - mongo
  #     - mysql
  #   command: sh -c "npm install && npm run dev"

