version: '3.1'
services:
  mongo:
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./containers/mongo/data:/data/db
    image: mongo:8.0.0-rc9
    restart: always
    env_file: .env
  mysql:
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./containers/mysql/data:/var/lib/mysql
    image: mysql:5.7
    restart: always
    env_file: .env

  