version: '3.1'
services:
  mongo:
    container_name: mongo
    ports:
      - 27017:27017
    # volumes:
    #   - ./containers/mongo:/data/db
    image: mongo:8.0.0-rc9
    env_file: .env
    networks:
      - network-test
  mysql:
    container_name: mysql
    ports:
      - 3306:3306
    # volumes:
    #   - ./containers/mysql:/var/lib/mysql
    image: mysql:5.7
    env_file: .env
    networks:
      - network-test
  data-faker:
    container_name: data-faker
    build:
      context: ./containers/fake-data
    working_dir: /app 
    environment:
      - MYSQL_HOST=mysql
    env_file: .env
    command: "./wait-for-it.sh mysql:3306 -- python fake-data-mysql.py"
    depends_on:
      - mysql
      - mongo
    networks:
      - network-test
networks:
  network-test:

  
  # backend:
  #   container_name: backend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./backend:/app
  #   image: node:lts-slim
  #   working_dir: /app 
  #   depends_on:
  #     - mongo
  #     - mysql
  #   command: sh -c "npm install && npm run dev"

